### ISSUE TITLE
No such file or directory: 'cache/Face_netG.pth'

### ISSUE THREAD

**Issue by xphsean12** [daooshee/Typography-with-Decor#3]
Hello.

When I run the runtext.py. The following traceback occur:

Traceback (most recent call last):
  File "FineTuning/generate.py", line 45, in <module>
    netG.load_state_dict(torch.load('cache/%s_netG.pth'%(opt.style_name), map_location=lambda storage, loc: storage))
  File "C:\Users\rayxu\Anaconda3\envs\pytorch_py3.7\lib\site-packages\torch\serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'cache/Face_netG.pth'
Error, cannot find text effect transfer result.

I try to figure it out but fail.

Thanks.

**Comment by xphsean12** [comment]
This is not the real problem. Sorry that I have obmit one important fact that the training have not been finished. The reason is that I am using Window 10 environment. 
If someone encounter problme such as 

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

You can be solved it with the help of  https://github.com/pytorch/tutorials/pull/337

Thanks.
