### ISSUE TITLE
I got issue when run runtest.py

### ISSUE THREAD

**Issue by sevaroy** [daooshee/Typography-with-Decor#5]
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

--- Basal Text Effect Transfer---
Traceback (most recent call last):
  File "FineTuning/generate.py", line 45, in <module>
    netG.load_state_dict(torch.load('cache/%s_netG.pth'%(opt.style_name), map_location=lambda storage, loc: storage))
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\Typography-with-Decor\lib\site-packages\torch\serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\Typography-with-Decor\lib\site-packages\torch\serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\Typography-with-Decor\lib\site-packages\torch\serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'cache/Face_netG.pth'
Error, cannot find text effect transfer result.

env
Python 3.5
Windows 10

**Comment by awalker0215** [comment]
congratulations on this problem was be solved.
just add `if __name__ == '__main__':` before` loader = iter(loader_)`
