### ISSUE TITLE
An error on cv2.resize()

### ISSUE THREAD

**Issue by Wenretium** [daooshee/Typography-with-Decor#6]
When I simply run runtest.py on what you provide, I meet this error:

 --- Decor Recomposition ---
Find 6 decor classes
Process the 0-th class, containing 371 elements............................Traceback (most recent call last):
  File "decor_recomposition.py", line 617, in <module>
    result, input_map, output_map, input_dir_map, output_dir_map = GOT.Move(Img,Cha,Seg,TargetImg,TargetCha, opt.style_name, opt.content_name)
  File "decor_recomposition.py", line 460, in Move
    deco = cv2.resize(deco,(new_size_y,new_size_x))
cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !dsize.empty() || >>>(inv_scale_x > 0 && inv_scale_y > 0) in function 'resize'

I found that new_size_x or new_size_y might be 0 in some cases and that caused the error. I try to insert these codes before cv2.resize() and only one style of all is successfully processed. 

if new_size_x == 0:
    break
if new_size_y == 0:
    break

Have you met this error before? I'm using opencv3.4.2 as yours and I don't think this is related to other packages.

**Comment by MalayJoshi2001** [comment]
Facing same issue. Any solution for this?
